Update style.css
The-Codesis/simple-static-website pull request #53
Opened 2020-10-01 08:10 UTC by karanmandve

Redesign your send button to improve its design.

2020-10-15 12:25 UTC, CapTen101 requested changes
Hi @karanmandve 
While doing any changes, always include the screenshot of *before* and *after*.
This helps in reviewing the changes better and fast

2020-10-15 14:27 UTC, karanmandve commented
Ok sir I remember next time.

On Thu, Oct 15, 2020, 5:55 PM Tushar Rohilla <notifications@github.com>
wrote:

> *@CapTen101* requested changes on this pull request.
>
> Hi @karanmandve <https://github.com/karanmandve>
> While doing any changes, always include the screenshot of *before* and
> *after*.
> This helps in reviewing the changes better and fast
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/The-Codesis/simple-static-website/pull/53#pullrequestreview-509320728>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOEDY7VJVH47ULXTOXA4VPTSK3S3PANCNFSM4SAC3EWA>
> .
>

2020-10-15 14:29 UTC, CapTen101 commented
Yeah, cool. But include them here now too

2020-10-16 03:11 UTC, karanmandve commented
Ok sir

On Thu, Oct 15, 2020, 7:59 PM Tushar Rohilla <notifications@github.com>
wrote:

> Yeah, cool. But include them here now too
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/The-Codesis/simple-static-website/pull/53#issuecomment-709364707>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOEDY7QRFZTPAZUY2DFQWI3SK4BODANCNFSM4SAC3EWA>
> .
>

2025-06-27 09:45 UTC, closed without merging